-- Auto-generated VectorCAST test script
-- Generated by vcast_automation
-- Source: C:\Users\sartjama\Desktop\Vcast\tests\fixtures\source\App_Scene.c
-- Unit: App_Scene

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:App_Scene_MainFunction
TEST.NEW
TEST.NAME:App_Scene_App_Scene_MainFunction_baseline_001
TEST.NOTES:
##ID##
App_Scene_App_Scene_MainFunction_baseline_001
##End.ID##
##Description##
Baseline skeleton test for function App_Scene_MainFunction.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Baseline execution intent.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_ForwardVision_FailSafe_Protocol_SignalMapping
TEST.NEW
TEST.NAME:App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_baseline_001
TEST.NOTES:
##ID##
App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_baseline_001
##End.ID##
##Description##
Baseline skeleton test for function Scene_ForwardVision_FailSafe_Protocol_SignalMapping.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Baseline execution intent.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_ForwardVision_FailSafe_Protocol_SignalMapping
TEST.NEW
TEST.NAME:App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_TeEBA_e_FullBlockage_NONE_002
TEST.NOTES:
##ID##
App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_TeEBA_e_FullBlockage_NONE_002
##End.ID##
##Description##
Targets switch case TeEBA_e_FullBlockage_NONE.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only switch case coverage for TeEBA_e_FullBlockage_NONE.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_ForwardVision_FailSafe_Protocol_SignalMapping
TEST.NEW
TEST.NAME:App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_TeEBA_e_FullBlockage_25_003
TEST.NOTES:
##ID##
App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_TeEBA_e_FullBlockage_25_003
##End.ID##
##Description##
Targets switch case TeEBA_e_FullBlockage_25.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only switch case coverage for TeEBA_e_FullBlockage_25.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_ForwardVision_FailSafe_Protocol_SignalMapping
TEST.NEW
TEST.NAME:App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_TeEBA_e_FullBlockage_50_004
TEST.NOTES:
##ID##
App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_TeEBA_e_FullBlockage_50_004
##End.ID##
##Description##
Targets switch case TeEBA_e_FullBlockage_50.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only switch case coverage for TeEBA_e_FullBlockage_50.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_ForwardVision_FailSafe_Protocol_SignalMapping
TEST.NEW
TEST.NAME:App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_TeEBA_e_FullBlockage_75_005
TEST.NOTES:
##ID##
App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_TeEBA_e_FullBlockage_75_005
##End.ID##
##Description##
Targets switch case TeEBA_e_FullBlockage_75.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only switch case coverage for TeEBA_e_FullBlockage_75.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_ForwardVision_FailSafe_Protocol_SignalMapping
TEST.NEW
TEST.NAME:App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_TeEBA_e_FullBlockage_99_006
TEST.NOTES:
##ID##
App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_TeEBA_e_FullBlockage_99_006
##End.ID##
##Description##
Targets switch case TeEBA_e_FullBlockage_99.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only switch case coverage for TeEBA_e_FullBlockage_99.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_ForwardVision_FailSafe_Protocol_SignalMapping
TEST.NEW
TEST.NAME:App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_TeEBA_e_FullBlockage_NOT_READY_007
TEST.NOTES:
##ID##
App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_TeEBA_e_FullBlockage_NOT_READY_007
##End.ID##
##Description##
Targets switch case TeEBA_e_FullBlockage_NOT_READY.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only switch case coverage for TeEBA_e_FullBlockage_NOT_READY.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_ForwardVision_FailSafe_Protocol_SignalMapping
TEST.NEW
TEST.NAME:App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_default_008
TEST.NOTES:
##ID##
App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_default_008
##End.ID##
##Description##
Targets switch case default.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only switch case coverage for default.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_ForwardVision_FailSafe_Protocol_SignalMapping
TEST.NEW
TEST.NAME:App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_TeEBA_e_PartialBlockage_NONE_009
TEST.NOTES:
##ID##
App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_TeEBA_e_PartialBlockage_NONE_009
##End.ID##
##Description##
Targets switch case TeEBA_e_PartialBlockage_NONE.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only switch case coverage for TeEBA_e_PartialBlockage_NONE.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_ForwardVision_FailSafe_Protocol_SignalMapping
TEST.NEW
TEST.NAME:App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_TeEBA_e_PartialBlockage_25_010
TEST.NOTES:
##ID##
App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_TeEBA_e_PartialBlockage_25_010
##End.ID##
##Description##
Targets switch case TeEBA_e_PartialBlockage_25.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only switch case coverage for TeEBA_e_PartialBlockage_25.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_ForwardVision_FailSafe_Protocol_SignalMapping
TEST.NEW
TEST.NAME:App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_TeEBA_e_PartialBlockage_50_011
TEST.NOTES:
##ID##
App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_TeEBA_e_PartialBlockage_50_011
##End.ID##
##Description##
Targets switch case TeEBA_e_PartialBlockage_50.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only switch case coverage for TeEBA_e_PartialBlockage_50.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_ForwardVision_FailSafe_Protocol_SignalMapping
TEST.NEW
TEST.NAME:App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_TeEBA_e_PartialBlockage_75_012
TEST.NOTES:
##ID##
App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_TeEBA_e_PartialBlockage_75_012
##End.ID##
##Description##
Targets switch case TeEBA_e_PartialBlockage_75.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only switch case coverage for TeEBA_e_PartialBlockage_75.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_ForwardVision_FailSafe_Protocol_SignalMapping
TEST.NEW
TEST.NAME:App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_TeEBA_e_PartialBlockage_99_013
TEST.NOTES:
##ID##
App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_TeEBA_e_PartialBlockage_99_013
##End.ID##
##Description##
Targets switch case TeEBA_e_PartialBlockage_99.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only switch case coverage for TeEBA_e_PartialBlockage_99.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_ForwardVision_FailSafe_Protocol_SignalMapping
TEST.NEW
TEST.NAME:App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_TeEBA_e_PartialBlockage_NOT_READY_014
TEST.NOTES:
##ID##
App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_TeEBA_e_PartialBlockage_NOT_READY_014
##End.ID##
##Description##
Targets switch case TeEBA_e_PartialBlockage_NOT_READY.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only switch case coverage for TeEBA_e_PartialBlockage_NOT_READY.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_ForwardVision_FailSafe_Protocol_SignalMapping
TEST.NEW
TEST.NAME:App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_default_015
TEST.NOTES:
##ID##
App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_default_015
##End.ID##
##Description##
Targets switch case default.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only switch case coverage for default.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_ForwardVision_FailSafe_Protocol_SignalMapping
TEST.NEW
TEST.NAME:App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_TeEBA_e_LowSun_NONE_016
TEST.NOTES:
##ID##
App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_TeEBA_e_LowSun_NONE_016
##End.ID##
##Description##
Targets switch case TeEBA_e_LowSun_NONE.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only switch case coverage for TeEBA_e_LowSun_NONE.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_ForwardVision_FailSafe_Protocol_SignalMapping
TEST.NEW
TEST.NAME:App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_TeEBA_e_LowSun_25_017
TEST.NOTES:
##ID##
App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_TeEBA_e_LowSun_25_017
##End.ID##
##Description##
Targets switch case TeEBA_e_LowSun_25.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only switch case coverage for TeEBA_e_LowSun_25.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_ForwardVision_FailSafe_Protocol_SignalMapping
TEST.NEW
TEST.NAME:App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_TeEBA_e_LowSun_50_018
TEST.NOTES:
##ID##
App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_TeEBA_e_LowSun_50_018
##End.ID##
##Description##
Targets switch case TeEBA_e_LowSun_50.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only switch case coverage for TeEBA_e_LowSun_50.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_ForwardVision_FailSafe_Protocol_SignalMapping
TEST.NEW
TEST.NAME:App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_TeEBA_e_LowSun_75_019
TEST.NOTES:
##ID##
App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_TeEBA_e_LowSun_75_019
##End.ID##
##Description##
Targets switch case TeEBA_e_LowSun_75.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only switch case coverage for TeEBA_e_LowSun_75.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_ForwardVision_FailSafe_Protocol_SignalMapping
TEST.NEW
TEST.NAME:App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_TeEBA_e_LowSun_99_020
TEST.NOTES:
##ID##
App_Scene_Scene_ForwardVision_FailSafe_Protocol_SignalMapping_switch_TeEBA_e_LowSun_99_020
##End.ID##
##Description##
Targets switch case TeEBA_e_LowSun_99.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only switch case coverage for TeEBA_e_LowSun_99.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_ForwardVision_Automatic_High_Beam_Assist_Degraded_SignalMapping
TEST.NEW
TEST.NAME:App_Scene_Scene_ForwardVision_Automatic_High_Beam_Assist_Degraded_SignalMapping_baseline_001
TEST.NOTES:
##ID##
App_Scene_Scene_ForwardVision_Automatic_High_Beam_Assist_Degraded_SignalMapping_baseline_001
##End.ID##
##Description##
Baseline skeleton test for function Scene_ForwardVision_Automatic_High_Beam_Assist_Degraded_SignalMapping.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Baseline execution intent.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_ForwardVision_Automatic_High_Beam_Assist_Degraded_SignalMapping
TEST.NEW
TEST.NAME:App_Scene_Scene_ForwardVision_Automatic_High_Beam_Assist_Degraded_SignalMapping_condition_true_002
TEST.NOTES:
##ID##
App_Scene_Scene_ForwardVision_Automatic_High_Beam_Assist_Degraded_SignalMapping_condition_true_002
##End.ID##
##Description##
Targets true branch of condition EyeQ_FailSafe_Protocol->IeEBA_bf_ImpactedTechnologies == HLB.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only true branch for condition at line 573.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_ForwardVision_Automatic_High_Beam_Assist_Degraded_SignalMapping
TEST.NEW
TEST.NAME:App_Scene_Scene_ForwardVision_Automatic_High_Beam_Assist_Degraded_SignalMapping_condition_false_003
TEST.NOTES:
##ID##
App_Scene_Scene_ForwardVision_Automatic_High_Beam_Assist_Degraded_SignalMapping_condition_false_003
##End.ID##
##Description##
Targets false branch of condition EyeQ_FailSafe_Protocol->IeEBA_bf_ImpactedTechnologies == HLB.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only false branch for condition at line 573.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_Environment_Illumination_Determination
TEST.NEW
TEST.NAME:App_Scene_Scene_Environment_Illumination_Determination_baseline_001
TEST.NOTES:
##ID##
App_Scene_Scene_Environment_Illumination_Determination_baseline_001
##End.ID##
##Description##
Baseline skeleton test for function Scene_Environment_Illumination_Determination.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Baseline execution intent.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_Environment_Illumination_Determination
TEST.NEW
TEST.NAME:App_Scene_Scene_Environment_Illumination_Determination_condition_true_002
TEST.NOTES:
##ID##
App_Scene_Scene_Environment_Illumination_Determination_condition_true_002
##End.ID##
##Description##
Targets true branch of condition (EyeQ_Common_Protocol->IeEBA_e_DaytimeIndicator == TeEBA_e_DaytimeIndicator_NIGHT) && (EyeQ_Light_Scene_VCL_Protocol->IeEBA_na_LSVBrightnessScore > (float32)0.3f ).
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only true branch for condition at line 615.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_Environment_Illumination_Determination
TEST.NEW
TEST.NAME:App_Scene_Scene_Environment_Illumination_Determination_condition_false_003
TEST.NOTES:
##ID##
App_Scene_Scene_Environment_Illumination_Determination_condition_false_003
##End.ID##
##Description##
Targets false branch of condition (EyeQ_Common_Protocol->IeEBA_e_DaytimeIndicator == TeEBA_e_DaytimeIndicator_NIGHT) && (EyeQ_Light_Scene_VCL_Protocol->IeEBA_na_LSVBrightnessScore > (float32)0.3f ).
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only false branch for condition at line 615.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_Environment_Illumination_Determination
TEST.NEW
TEST.NAME:App_Scene_Scene_Environment_Illumination_Determination_condition_true_004
TEST.NOTES:
##ID##
App_Scene_Scene_Environment_Illumination_Determination_condition_true_004
##End.ID##
##Description##
Targets true branch of condition (EyeQ_Common_Protocol->IeEBA_e_DaytimeIndicator == TeEBA_e_DaytimeIndicator_NIGHT) && (EyeQ_Light_Scene_VCL_Protocol->IeEBA_na_LSVBrightnessScore < (float32)0.2f ).
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only true branch for condition at line 622.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_Environment_Illumination_Determination
TEST.NEW
TEST.NAME:App_Scene_Scene_Environment_Illumination_Determination_condition_false_005
TEST.NOTES:
##ID##
App_Scene_Scene_Environment_Illumination_Determination_condition_false_005
##End.ID##
##Description##
Targets false branch of condition (EyeQ_Common_Protocol->IeEBA_e_DaytimeIndicator == TeEBA_e_DaytimeIndicator_NIGHT) && (EyeQ_Light_Scene_VCL_Protocol->IeEBA_na_LSVBrightnessScore < (float32)0.2f ).
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only false branch for condition at line 622.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_Environment_Illumination_Determination
TEST.NEW
TEST.NAME:App_Scene_Scene_Environment_Illumination_Determination_condition_true_006
TEST.NOTES:
##ID##
App_Scene_Scene_Environment_Illumination_Determination_condition_true_006
##End.ID##
##Description##
Targets true branch of condition EyeQ_Common_Protocol->IeEBA_e_DaytimeIndicator == TeEBA_e_DaytimeIndicator_DAY.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only true branch for condition at line 628.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_Environment_Illumination_Determination
TEST.NEW
TEST.NAME:App_Scene_Scene_Environment_Illumination_Determination_condition_false_007
TEST.NOTES:
##ID##
App_Scene_Scene_Environment_Illumination_Determination_condition_false_007
##End.ID##
##Description##
Targets false branch of condition EyeQ_Common_Protocol->IeEBA_e_DaytimeIndicator == TeEBA_e_DaytimeIndicator_DAY.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only false branch for condition at line 628.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_Environment_Illumination_Determination
TEST.NEW
TEST.NAME:App_Scene_Scene_Environment_Illumination_Determination_condition_true_008
TEST.NOTES:
##ID##
App_Scene_Scene_Environment_Illumination_Determination_condition_true_008
##End.ID##
##Description##
Targets true branch of condition EyeQ_Common_Protocol->IeEBA_e_DaytimeIndicator == TeEBA_e_DaytimeIndicator_NA.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only true branch for condition at line 634.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_Environment_Illumination_Determination
TEST.NEW
TEST.NAME:App_Scene_Scene_Environment_Illumination_Determination_condition_false_009
TEST.NOTES:
##ID##
App_Scene_Scene_Environment_Illumination_Determination_condition_false_009
##End.ID##
##Description##
Targets false branch of condition EyeQ_Common_Protocol->IeEBA_e_DaytimeIndicator == TeEBA_e_DaytimeIndicator_NA.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only false branch for condition at line 634.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_FrontVision_LimitedAccess_RoadType
TEST.NEW
TEST.NAME:App_Scene_Scene_FrontVision_LimitedAccess_RoadType_baseline_001
TEST.NOTES:
##ID##
App_Scene_Scene_FrontVision_LimitedAccess_RoadType_baseline_001
##End.ID##
##Description##
Baseline skeleton test for function Scene_FrontVision_LimitedAccess_RoadType.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Baseline execution intent.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_FrontVision_LimitedAccess_RoadType
TEST.NEW
TEST.NAME:App_Scene_Scene_FrontVision_LimitedAccess_RoadType_condition_true_002
TEST.NOTES:
##ID##
App_Scene_Scene_FrontVision_LimitedAccess_RoadType_condition_true_002
##End.ID##
##Description##
Targets true branch of condition EyeQ_Common_Protocol->IeEBA_e_COMRoadType == TeEBA_e_COMRoadType_HIGHWAY.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only true branch for condition at line 670.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_FrontVision_LimitedAccess_RoadType
TEST.NEW
TEST.NAME:App_Scene_Scene_FrontVision_LimitedAccess_RoadType_condition_false_003
TEST.NOTES:
##ID##
App_Scene_Scene_FrontVision_LimitedAccess_RoadType_condition_false_003
##End.ID##
##Description##
Targets false branch of condition EyeQ_Common_Protocol->IeEBA_e_COMRoadType == TeEBA_e_COMRoadType_HIGHWAY.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only false branch for condition at line 670.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_FrontVision_LimitedAccess_RoadType
TEST.NEW
TEST.NAME:App_Scene_Scene_FrontVision_LimitedAccess_RoadType_condition_true_004
TEST.NOTES:
##ID##
App_Scene_Scene_FrontVision_LimitedAccess_RoadType_condition_true_004
##End.ID##
##Description##
Targets true branch of condition (EyeQ_Common_Protocol->IeEBA_e_COMRoadType == TeEBA_e_COMRoadType_INTERURBAN )||(EyeQ_Common_Protocol->IeEBA_e_COMRoadType == TeEBA_e_COMRoadType_URBAN ).
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only true branch for condition at line 676.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_FrontVision_LimitedAccess_RoadType
TEST.NEW
TEST.NAME:App_Scene_Scene_FrontVision_LimitedAccess_RoadType_condition_false_005
TEST.NOTES:
##ID##
App_Scene_Scene_FrontVision_LimitedAccess_RoadType_condition_false_005
##End.ID##
##Description##
Targets false branch of condition (EyeQ_Common_Protocol->IeEBA_e_COMRoadType == TeEBA_e_COMRoadType_INTERURBAN )||(EyeQ_Common_Protocol->IeEBA_e_COMRoadType == TeEBA_e_COMRoadType_URBAN ).
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only false branch for condition at line 676.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_FrontVision_LimitedAccess_RoadType
TEST.NEW
TEST.NAME:App_Scene_Scene_FrontVision_LimitedAccess_RoadType_condition_true_006
TEST.NOTES:
##ID##
App_Scene_Scene_FrontVision_LimitedAccess_RoadType_condition_true_006
##End.ID##
##Description##
Targets true branch of condition EyeQ_Common_Protocol->IeEBA_e_COMRoadType == TeEBA_e_COMRoadType_UNKNOWN.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only true branch for condition at line 681.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_FrontVision_LimitedAccess_RoadType
TEST.NEW
TEST.NAME:App_Scene_Scene_FrontVision_LimitedAccess_RoadType_condition_false_007
TEST.NOTES:
##ID##
App_Scene_Scene_FrontVision_LimitedAccess_RoadType_condition_false_007
##End.ID##
##Description##
Targets false branch of condition EyeQ_Common_Protocol->IeEBA_e_COMRoadType == TeEBA_e_COMRoadType_UNKNOWN.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only false branch for condition at line 681.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_Construction_Area_Information
TEST.NEW
TEST.NAME:App_Scene_Scene_Construction_Area_Information_baseline_001
TEST.NOTES:
##ID##
App_Scene_Scene_Construction_Area_Information_baseline_001
##End.ID##
##Description##
Baseline skeleton test for function Scene_Construction_Area_Information.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Baseline execution intent.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_BlockageStatus_Determination
TEST.NEW
TEST.NAME:App_Scene_Scene_BlockageStatus_Determination_baseline_001
TEST.NOTES:
##ID##
App_Scene_Scene_BlockageStatus_Determination_baseline_001
##End.ID##
##Description##
Baseline skeleton test for function Scene_BlockageStatus_Determination.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Baseline execution intent.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_BlockageStatus_Determination
TEST.NEW
TEST.NAME:App_Scene_Scene_BlockageStatus_Determination_condition_true_002
TEST.NOTES:
##ID##
App_Scene_Scene_BlockageStatus_Determination_condition_true_002
##End.ID##
##Description##
Targets true branch of condition ( TeEBA_e_FullBlockage_NOT_READY == EyeQ_FailSafe_Protocol->IeEBA_e_FullBlockage )
            && ( TeEBA_e_PartialBlockage_NOT_READY == EyeQ_FailSafe_Protocol->IeEBA_e_PartialBlockage ).
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only true branch for condition at line 935.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_BlockageStatus_Determination
TEST.NEW
TEST.NAME:App_Scene_Scene_BlockageStatus_Determination_condition_false_003
TEST.NOTES:
##ID##
App_Scene_Scene_BlockageStatus_Determination_condition_false_003
##End.ID##
##Description##
Targets false branch of condition ( TeEBA_e_FullBlockage_NOT_READY == EyeQ_FailSafe_Protocol->IeEBA_e_FullBlockage )
            && ( TeEBA_e_PartialBlockage_NOT_READY == EyeQ_FailSafe_Protocol->IeEBA_e_PartialBlockage ).
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only false branch for condition at line 935.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_BlockageStatus_Determination
TEST.NEW
TEST.NAME:App_Scene_Scene_BlockageStatus_Determination_condition_true_004
TEST.NOTES:
##ID##
App_Scene_Scene_BlockageStatus_Determination_condition_true_004
##End.ID##
##Description##
Targets true branch of condition ( TeEBA_e_FullBlockage_25 == EyeQ_FailSafe_Protocol->IeEBA_e_FullBlockage )
            || ( TeEBA_e_FullBlockage_50 == EyeQ_FailSafe_Protocol->IeEBA_e_FullBlockage )
            || ( TeEBA_e_FullBlockage_75 == EyeQ_FailSafe_Protocol->IeEBA_e_FullBlockage )
            || ( TeEBA_e_FullBlockage_99 == EyeQ_FailSafe_Protocol->IeEBA_e_FullBlockage ).
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only true branch for condition at line 942.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_BlockageStatus_Determination
TEST.NEW
TEST.NAME:App_Scene_Scene_BlockageStatus_Determination_condition_false_005
TEST.NOTES:
##ID##
App_Scene_Scene_BlockageStatus_Determination_condition_false_005
##End.ID##
##Description##
Targets false branch of condition ( TeEBA_e_FullBlockage_25 == EyeQ_FailSafe_Protocol->IeEBA_e_FullBlockage )
            || ( TeEBA_e_FullBlockage_50 == EyeQ_FailSafe_Protocol->IeEBA_e_FullBlockage )
            || ( TeEBA_e_FullBlockage_75 == EyeQ_FailSafe_Protocol->IeEBA_e_FullBlockage )
            || ( TeEBA_e_FullBlockage_99 == EyeQ_FailSafe_Protocol->IeEBA_e_FullBlockage ).
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only false branch for condition at line 942.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_BlockageStatus_Determination
TEST.NEW
TEST.NAME:App_Scene_Scene_BlockageStatus_Determination_condition_true_006
TEST.NOTES:
##ID##
App_Scene_Scene_BlockageStatus_Determination_condition_true_006
##End.ID##
##Description##
Targets true branch of condition ( TeEBA_e_PartialBlockage_25 == EyeQ_FailSafe_Protocol->IeEBA_e_PartialBlockage )
            || ( TeEBA_e_PartialBlockage_50 == EyeQ_FailSafe_Protocol->IeEBA_e_PartialBlockage )
            || ( TeEBA_e_PartialBlockage_75 == EyeQ_FailSafe_Protocol->IeEBA_e_PartialBlockage )
            || ( TeEBA_e_PartialBlockage_99 == EyeQ_FailSafe_Protocol->IeEBA_e_PartialBlockage ).
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only true branch for condition at line 951.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_BlockageStatus_Determination
TEST.NEW
TEST.NAME:App_Scene_Scene_BlockageStatus_Determination_condition_false_007
TEST.NOTES:
##ID##
App_Scene_Scene_BlockageStatus_Determination_condition_false_007
##End.ID##
##Description##
Targets false branch of condition ( TeEBA_e_PartialBlockage_25 == EyeQ_FailSafe_Protocol->IeEBA_e_PartialBlockage )
            || ( TeEBA_e_PartialBlockage_50 == EyeQ_FailSafe_Protocol->IeEBA_e_PartialBlockage )
            || ( TeEBA_e_PartialBlockage_75 == EyeQ_FailSafe_Protocol->IeEBA_e_PartialBlockage )
            || ( TeEBA_e_PartialBlockage_99 == EyeQ_FailSafe_Protocol->IeEBA_e_PartialBlockage ).
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only false branch for condition at line 951.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_BlockageIndication_Determination
TEST.NEW
TEST.NAME:App_Scene_Scene_BlockageIndication_Determination_baseline_001
TEST.NOTES:
##ID##
App_Scene_Scene_BlockageIndication_Determination_baseline_001
##End.ID##
##Description##
Baseline skeleton test for function Scene_BlockageIndication_Determination.
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Baseline execution intent.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_BlockageIndication_Determination
TEST.NEW
TEST.NAME:App_Scene_Scene_BlockageIndication_Determination_condition_true_002
TEST.NOTES:
##ID##
App_Scene_Scene_BlockageIndication_Determination_condition_true_002
##End.ID##
##Description##
Targets true branch of condition ( FVBlkgSts_FULL_BLOCKAGE == SrlDat423_PrtctdPDU.FVBlkgSts )
            || ( FVBlkgSts_PARTIAL_BLOCKAGE == SrlDat423_PrtctdPDU.FVBlkgSts ).
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only true branch for condition at line 991.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END

TEST.UNIT:App_Scene
TEST.SUBPROGRAM:Scene_BlockageIndication_Determination
TEST.NEW
TEST.NAME:App_Scene_Scene_BlockageIndication_Determination_condition_false_003
TEST.NOTES:
##ID##
App_Scene_Scene_BlockageIndication_Determination_condition_false_003
##End.ID##
##Description##
Targets false branch of condition ( FVBlkgSts_FULL_BLOCKAGE == SrlDat423_PrtctdPDU.FVBlkgSts )
            || ( FVBlkgSts_PARTIAL_BLOCKAGE == SrlDat423_PrtctdPDU.FVBlkgSts ).
##End.Description##
##ReviewID##
TBD
##End.ReviewID##
##Status##
Draft
##End.Status##
##Notes##
Intent-only false branch for condition at line 991.
##End.Notes##
##GUID##
TBD
##End.GUID##
##ASIL##
QM
##End.ASIL##
TEST.END_NOTES:
-- No safe scalar TEST.VALUE generated; manual VectorCAST assignment may be required.
TEST.END
