"""
coverage_feedback.py — Coverage-driven targeted test case generation.

Analyzes coverage reports and generates follow-up test cases targeting
uncovered branches and conditions.
"""

from __future__ import annotations

from vcast_automation.models.core import TestCasePlan, FunctionModel


def analyze_uncovered_targets(report: dict) -> list[str]:
    """
    Extract uncovered branches/conditions from coverage report.
    
    Args:
        report: Coverage report dict with keys like:
            - uncovered_branches: [line_numbers]
            - uncovered_conditions: [condition_expressions]
            - partially_covered_branches: [...]
    
    Returns:
        List of uncovered target descriptions.
    """
    targets = []
    
    if "uncovered_branches" in report:
        for line in report["uncovered_branches"]:
            targets.append(f"branch_at_line_{line}")
    
    if "uncovered_conditions" in report:
        for cond in report["uncovered_conditions"]:
            targets.append(f"condition_{cond}")
    
    if "partially_covered_branches" in report:
        for line in report["partially_covered_branches"]:
            targets.append(f"partial_branch_at_line_{line}")
    
    return targets


def build_followup_cases(
    function_model: FunctionModel,
    uncovered_targets: list[str],
    config: dict,
) -> list[TestCasePlan]:
    """
    Generate targeted test cases for uncovered branches/conditions.
    
    Args:
        function_model: Function to generate cases for.
        uncovered_targets: List of uncovered target identifiers.
        config: Generation configuration.
    
    Returns:
        List of new TestCasePlan objects targeting uncovered code.
    """
    cases = []
    
    max_followup = config.get("max_feedback_iterations", 0)
    if max_followup <= 0:
        return cases
    
    # For each uncovered target, try to generate a case
    for target in uncovered_targets[:max_followup]:
        case = _generate_case_for_target(function_model, target, config)
        if case:
            case.generation_stage = "coverage_feedback"
            case.coverage_targets = [target]
            cases.append(case)
    
    return cases


def validate_feedback_progress(
    previous_coverage: float,
    current_coverage: float,
) -> tuple[bool, str]:
    """
    Check if coverage improved after feedback iteration.
    
    Args:
        previous_coverage: Coverage % before feedback cases.
        current_coverage: Coverage % after feedback cases.
    
    Returns:
        Tuple of (improved: bool, message: str).
    """
    improvement = current_coverage - previous_coverage
    
    if improvement > 0:
        return True, f"Coverage improved by {improvement:.1f}%"
    elif improvement == 0:
        return False, "Coverage feedback did not improve coverage"
    else:
        return False, f"Coverage regressed by {-improvement:.1f}%"


# Internal helpers

def _generate_case_for_target(
    function_model: FunctionModel,
    target: str,
    config: dict,
) -> TestCasePlan | None:
    """
    Generate a single test case targeting an uncovered branch/condition.
    
    Args:
        function_model: Function to test.
        target: Target identifier (e.g., "branch_at_line_42").
        config: Generation config.
    
    Returns:
        TestCasePlan or None if generation fails.
    """
    # Parse target to find relevant condition
    if "condition_" in target:
        return _generate_for_condition(function_model, target, config)
    elif "branch_at_line" in target:
        return _generate_for_branch(function_model, target, config)
    
    return None


def _generate_for_condition(
    function_model: FunctionModel,
    target: str,
    config: dict,
) -> TestCasePlan | None:
    """Generate case for uncovered condition."""
    # Extract condition expression from target (simplified)
    # In a real implementation, would look up condition in function_model
    
    test_name = f"{function_model.unit_name}_{function_model.function_name}_feedback_{target}"
    
    case = TestCasePlan(
        test_case_id=test_name,
        test_name=test_name,
        unit_name=function_model.unit_name,
        subprogram_name=function_model.vcast_subprogram_name,
        source_path=function_model.source_path,
        function_name=function_model.function_name,
        family="feedback_condition",
        description=f"Feedback case targeting {target}",
        coverage_intent=f"Drive condition at {target}",
        notes="Generated by coverage feedback engine",
    )
    
    return case


def _generate_for_branch(
    function_model: FunctionModel,
    target: str,
    config: dict,
) -> TestCasePlan | None:
    """Generate case for uncovered branch."""
    # Extract line number from target
    # In a real implementation, would analyze the branch at that line
    
    test_name = f"{function_model.unit_name}_{function_model.function_name}_feedback_{target}"
    
    case = TestCasePlan(
        test_case_id=test_name,
        test_name=test_name,
        unit_name=function_model.unit_name,
        subprogram_name=function_model.vcast_subprogram_name,
        source_path=function_model.source_path,
        function_name=function_model.function_name,
        family="feedback_branch",
        description=f"Feedback case targeting {target}",
        coverage_intent=f"Drive branch at {target}",
        notes="Generated by coverage feedback engine",
    )
    
    return case
