from __future__ import annotations

import json
from pathlib import Path
from typing import Any


DEFAULT_CONFIG: dict[str, Any] = {
    "tool": {"name": "UTAutomation", "version": 1},
    "project": {"name": "VectorCASTProject", "author": "AutoGenerated"},
    "defaults": {
        "unit_name_strategy": "source_stem",
        "environment_name_pattern": "{unit}_ENV",
        "output_file_pattern": "{unit}.tst",
    },
    "input": {
        "source_roots": [],
        "source_files": [],
        "include_extensions": [
            ".c",
            ".h",
            ".cpp",
            ".hpp",
            ".cc",
            ".cxx",
            ".hh",
            ".hxx",
        ],
        "exclude_dirs": ["build", "generated", "vendor", "third_party", ".git", "out"],
        "exclude_files": ["*_pb.c", "*_generated.c"],
    },
    "generation": {
        "mode": "skeleton",
        "output_dir": "./vcast_output",
        "test_naming_pattern": "TC_{function}_UT_{index:03d}",
        "default_status": "In Review",
        "default_priority": "High",
        "default_asil": [
            "Statement Coverage",
            "Branch Coverage",
            "MC/DC Coverage",
            "control flow verification",
            "visual inspection",
        ],
        "max_tests_per_function": 20,
        "enable_baseline_cases": True,
        "enable_condition_cases": True,
        "enable_switch_cases": True,
        "enable_loop_cases": True,
        "enable_rich_expected": False,
        "enable_project_rules": False,
        "enable_sample_traceability": False,
        "enable_sample_expected": False,
    },
    "vectorcast": {
        "header_banner": "",
        "environment_name": "",
        "unit_name_strategy": "source_stem",
        "omit_unsafe_values": True,
        "script_features": [
            "C_DIRECT_ARRAY_INDEXING",
            "CPP_CLASS_OBJECT_REVISION",
            "MULTIPLE_UUT_SUPPORT",
            "REMOVED_CL_PREFIX",
            "MIXED_CASE_NAMES",
            "STATIC_HEADER_FUNCS_IN_UUTS",
            "VCAST_MAIN_NOT_RENAMED",
        ],
    },
    "metadata": {
        "default_status": "In Review",
        "default_priority": "High",
        "default_asil": [
            "Statement Coverage",
            "Branch Coverage",
            "MC/DC Coverage",
            "control flow verification",
            "visual inspection",
        ],
    },
    "traceability": {
        "reviewid_xlsm_path": "",
        "guid_mapping_json": "",
        "ea_eapx_path": "",
        "ea_eapx_backend": "auto",
        "missing_review_id": "TBD",
        "missing_guid": "TBD",
    },
    "rules": {
        "enable_project_rules": False,
        "enable_expected_from_mapping": False,
    },
    "units": {},
    "validation": {"warn_on_tbd_traceability": True},
}


def _merge_dict(base: dict[str, Any], override: dict[str, Any]) -> dict[str, Any]:
    result = dict(base)

    for key, value in override.items():
        if isinstance(value, dict) and isinstance(result.get(key), dict):
            result[key] = _merge_dict(result[key], value)
        else:
            result[key] = value

    return result


def _strip_inline_comment(line: str) -> str:
    in_single = False
    in_double = False

    for index, char in enumerate(line):
        if char == "'" and not in_double:
            in_single = not in_single
        elif char == '"' and not in_single:
            in_double = not in_double
        elif char == "#" and not in_single and not in_double:
            return line[:index].rstrip()

    return line.rstrip()


def _parse_scalar(value: str) -> Any:
    value = value.strip()

    if value == "":
        return ""

    if value == "[]":
        return []

    if value == "{}":
        return {}

    lower = value.lower()

    if lower == "true":
        return True

    if lower == "false":
        return False

    if lower in {"null", "none", "~"}:
        return None

    if (
        (value.startswith('"') and value.endswith('"'))
        or (value.startswith("'") and value.endswith("'"))
    ):
        return value[1:-1]

    try:
        return int(value)
    except ValueError:
        pass

    return value


def _prepare_yaml_lines(text: str) -> list[tuple[int, str]]:
    lines: list[tuple[int, str]] = []

    for raw_line in text.splitlines():
        if not raw_line.strip():
            continue

        cleaned = _strip_inline_comment(raw_line)

        if not cleaned.strip():
            continue

        stripped = cleaned.lstrip()

        if stripped.startswith("#"):
            continue

        indent = len(cleaned) - len(stripped)
        lines.append((indent, stripped))

    return lines


def _parse_yaml_subset(text: str) -> dict[str, Any]:
    lines = _prepare_yaml_lines(text)
    index = 0

    def next_content_indent(start: int) -> int | None:
        if start >= len(lines):
            return None
        return lines[start][0]

    def parse_mapping(expected_indent: int) -> dict[str, Any]:
        nonlocal index

        result: dict[str, Any] = {}

        while index < len(lines):
            indent, content = lines[index]

            if indent < expected_indent:
                break

            if indent > expected_indent:
                break

            if content.startswith("- "):
                break

            if ":" not in content:
                index += 1
                continue

            key, raw_value = content.split(":", 1)
            key = key.strip()
            raw_value = raw_value.strip()

            index += 1

            if raw_value:
                result[key] = _parse_scalar(raw_value)
                continue

            child_indent = next_content_indent(index)

            if child_indent is None or child_indent <= indent:
                result[key] = {}
                continue

            if index < len(lines) and lines[index][1].startswith("- "):
                result[key] = parse_list(child_indent)
            else:
                result[key] = parse_mapping(child_indent)

        return result

    def parse_list(expected_indent: int) -> list[Any]:
        nonlocal index

        result: list[Any] = []

        while index < len(lines):
            indent, content = lines[index]

            if indent < expected_indent:
                break

            if indent != expected_indent or not content.startswith("- "):
                break

            item_text = content[2:].strip()
            index += 1

            if item_text == "":
                child_indent = next_content_indent(index)

                if child_indent is None or child_indent <= indent:
                    result.append(None)
                elif index < len(lines) and lines[index][1].startswith("- "):
                    result.append(parse_list(child_indent))
                else:
                    result.append(parse_mapping(child_indent))

            elif ": " in item_text and not item_text.startswith(("'", '"')):
                key, raw_value = item_text.split(":", 1)
                item: dict[str, Any] = {}
                item[key.strip()] = _parse_scalar(raw_value.strip())

                child_indent = next_content_indent(index)

                if child_indent is not None and child_indent > indent:
                    extra = parse_mapping(child_indent)
                    item.update(extra)

                result.append(item)

            else:
                result.append(_parse_scalar(item_text))

        return result

    if not lines:
        return {}

    return parse_mapping(lines[0][0])


def _parse_simple_yaml(text: str) -> dict[str, Any]:
    text = text.strip()

    if not text:
        return {}

    try:
        import yaml  # type: ignore

        data = yaml.safe_load(text)
        return data or {}
    except Exception:
        pass

    if text.startswith("{") or text.startswith("["):
        try:
            data = json.loads(text)
            return data or {}
        except json.JSONDecodeError:
            pass

    return _parse_yaml_subset(text)


def load_config(path: str | Path | None = None) -> dict[str, Any]:
    if path is None:
        return DEFAULT_CONFIG

    cfg_path = Path(path)

    if str(cfg_path).lower().endswith(".arxml"):
        raise NotImplementedError(
            "ARXML config parsing is not implemented yet. Use YAML as the official UTAutomation config format."
        )

    if not cfg_path.exists():
        return DEFAULT_CONFIG

    text = cfg_path.read_text(encoding="utf-8")
    user_cfg = _parse_simple_yaml(text)

    if not isinstance(user_cfg, dict):
        user_cfg = {}

    return _merge_dict(DEFAULT_CONFIG, user_cfg)


def write_default_config(path: str | Path = "vcastgen.yaml") -> None:
    content = """tool:
  name: UTAutomation
  version: 1

project:
  name: VectorCASTProject
  author: AutoGenerated

defaults:
  unit_name_strategy: source_stem
  environment_name_pattern: "{unit}_ENV"
  output_file_pattern: "{unit}.tst"

input:
  source_roots: []
  source_files: []
  include_extensions:
    - .c
    - .h
    - .cpp
    - .hpp
    - .cc
    - .cxx
    - .hh
    - .hxx
  exclude_dirs:
    - build
    - generated
    - vendor
    - third_party
    - .git
    - out
  exclude_files:
    - "*_pb.c"
    - "*_generated.c"

generation:
  mode: skeleton
  output_dir: ./vcast_output
  test_naming_pattern: "TC_{function}_UT_{index:03d}"
  default_status: In Review
  default_priority: High
  default_asil:
    - Statement Coverage
    - Branch Coverage
    - MC/DC Coverage
    - control flow verification
    - visual inspection
  max_tests_per_function: 20
  enable_baseline_cases: true
  enable_condition_cases: true
  enable_switch_cases: true
  enable_loop_cases: true
  enable_rich_expected: false
  enable_project_rules: false
  enable_sample_traceability: false
  enable_sample_expected: false

metadata:
  default_status: In Review
  default_priority: High
  default_asil:
    - Statement Coverage
    - Branch Coverage
    - MC/DC Coverage
    - control flow verification
    - visual inspection

traceability:
  reviewid_xlsm_path: ""
  guid_mapping_json: ""
  ea_eapx_path: ""
  ea_eapx_backend: auto
  missing_review_id: TBD
  missing_guid: TBD

rules:
  enable_project_rules: false
  enable_expected_from_mapping: false

vectorcast:
  header_banner: ""
  environment_name: ""
  unit_name_strategy: source_stem
  omit_unsafe_values: true
  script_features:
    - C_DIRECT_ARRAY_INDEXING
    - CPP_CLASS_OBJECT_REVISION
    - MULTIPLE_UUT_SUPPORT
    - REMOVED_CL_PREFIX
    - MIXED_CASE_NAMES
    - STATIC_HEADER_FUNCS_IN_UUTS
    - VCAST_MAIN_NOT_RENAMED

units: {}

validation:
  warn_on_tbd_traceability: true
"""
    Path(path).write_text(content, encoding="utf-8")
